# BuildMode Configuration

# Duration of build mode session in minutes
build-duration-minutes: 60

# Cooldown between sessions in minutes
cooldown-minutes: 1

# Display options
bossbar: true
scoreboard: false

# Allow redstone components
allowed-redstone: true

# Item restriction mode (blacklist or whitelist)
restriction-mode: blacklist

# Blacklist of items not allowed in build mode
blacklist:
  # Ores & Raw Blocks
  - COAL_ORE
  - IRON_ORE
  - GOLD_ORE
  - COPPER_ORE
  - DIAMOND_ORE
  - EMERALD_ORE
  - ANCIENT_DEBRIS
  - REDSTONE_ORE
  - LAPIS_ORE
  - QUARTZ_ORE
  - DEEPSLATE_COAL_ORE
  - DEEPSLATE_IRON_ORE
  - DEEPSLATE_GOLD_ORE
  - DEEPSLATE_COPPER_ORE
  - DEEPSLATE_DIAMOND_ORE
  - DEEPSLATE_EMERALD_ORE
  - DEEPSLATE_REDSTONE_ORE
  - DEEPSLATE_LAPIS_ORE
  
  # Mineral Blocks
  - IRON_BLOCK
  - GOLD_BLOCK
  - RAW_IRON_BLOCK
  - RAW_GOLD_BLOCK
  - RAW_COPPER_BLOCK
  - DIAMOND_BLOCK
  - EMERALD_BLOCK
  - COPPER_BLOCK
  - WAXED_COPPER_BLOCK
  - EXPOSED_COPPER
  - WAXED_EXPOSED_COPPER
  - WEATHERED_COPPER
  - WAXED_WEATHERED_COPPER
  - OXIDIZED_COPPER
  - WAXED_OXIDIZED_COPPER
  - NETHERITE_BLOCK
  - LAPIS_BLOCK
  - AMETHYST_BLOCK
  - BUDDING_AMETHYST
  
  # Ingots / Nuggets / Gems
  - IRON_INGOT
  - GOLD_INGOT
  - COPPER_INGOT
  - NETHERITE_INGOT
  - NETHERITE_SCRAP
  - GOLD_NUGGET
  - IRON_NUGGET
  - DIAMOND
  - EMERALD
  - LAPIS_LAZULI
  - AMETHYST_SHARD
  - RAW_IRON
  - RAW_GOLD
  - RAW_COPPER
  
  # Combat & Utility
  - WOODEN_SWORD
  - STONE_SWORD
  - IRON_SWORD
  - GOLDEN_SWORD
  - DIAMOND_SWORD
  - NETHERITE_SWORD
  - IRON_AXE
  - GOLDEN_AXE
  - DIAMOND_AXE
  - NETHERITE_AXE
  - LEATHER_HELMET
  - LEATHER_CHESTPLATE
  - LEATHER_LEGGINGS
  - LEATHER_BOOTS
  - CHAINMAIL_HELMET
  - CHAINMAIL_CHESTPLATE
  - CHAINMAIL_LEGGINGS
  - CHAINMAIL_BOOTS
  - IRON_HELMET
  - IRON_CHESTPLATE
  - IRON_LEGGINGS
  - IRON_BOOTS
  - GOLDEN_HELMET
  - GOLDEN_CHESTPLATE
  - GOLDEN_LEGGINGS
  - GOLDEN_BOOTS
  - DIAMOND_HELMET
  - DIAMOND_CHESTPLATE
  - DIAMOND_LEGGINGS
  - DIAMOND_BOOTS
  - NETHERITE_HELMET
  - NETHERITE_CHESTPLATE
  - NETHERITE_LEGGINGS
  - NETHERITE_BOOTS
  - SHIELD
  - BOW
  - CROSSBOW
  - TRIDENT
  - ELYTRA
  - ARROW
  - SPECTRAL_ARROW
  - TIPPED_ARROW
  - FIREWORK_ROCKET
  - TOTEM_OF_UNDYING
  
  # Mobility / Dimension
  - ENDER_PEARL
  - EYE_OF_ENDER
  - OBSIDIAN
  - CRYING_OBSIDIAN
  - END_PORTAL_FRAME
  - RESPAWN_ANCHOR
  - SHULKER_BOX
  - WHITE_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - YELLOW_SHULKER_BOX
  - LIME_SHULKER_BOX
  - PINK_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - LIGHT_GRAY_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - RED_SHULKER_BOX
  - BLACK_SHULKER_BOX
  - END_CRYSTAL
  
  # Consumables & Brewing
  - POTION
  - SPLASH_POTION
  - LINGERING_POTION
  - EXPERIENCE_BOTTLE
  - GOLDEN_APPLE
  - ENCHANTED_GOLDEN_APPLE
  - APPLE
  - BREAD
  - COOKED_BEEF
  - COOKED_CHICKEN
  - COOKED_MUTTON
  - COOKED_PORKCHOP
  - COOKED_RABBIT
  - COOKED_COD
  - COOKED_SALMON
  - BREWING_STAND
  - CAULDRON
  - BLAZE_ROD
  - BLAZE_POWDER
  - NETHER_WART
  - GHAST_TEAR
  - FERMENTED_SPIDER_EYE
  - GLISTERING_MELON_SLICE
  - GOLDEN_CARROT
  - RABBIT_FOOT
  - PHANTOM_MEMBRANE
  
  # Spawn Eggs & Utility Blocks
  - SPAWNER
  - COMMAND_BLOCK
  - CHAIN_COMMAND_BLOCK
  - REPEATING_COMMAND_BLOCK
  - STRUCTURE_BLOCK
  - JIGSAW
  - BARRIER
  - LIGHT
  - DEBUG_STICK
  
  # Storage & Automation
  - HOPPER
  - CHEST
  - TRAPPED_CHEST
  - BARREL
  - DROPPER
  - DISPENSER
  - HOPPER_MINECART
  - CHEST_MINECART
  - BUNDLE
  
  # Enchanting / Smithing
  - ENCHANTING_TABLE
  - ANVIL
  - CHIPPED_ANVIL
  - DAMAGED_ANVIL
  - GRINDSTONE
  - SMITHING_TABLE
  - BOOKSHELF
  - ENCHANTED_BOOK
  - BOOK
  
  # Others
  - MUSIC_DISC_13
  - MUSIC_DISC_CAT
  - MUSIC_DISC_BLOCKS
  - MUSIC_DISC_CHIRP
  - MUSIC_DISC_FAR
  - MUSIC_DISC_MALL
  - MUSIC_DISC_MELLOHI
  - MUSIC_DISC_STAL
  - MUSIC_DISC_STRAD
  - MUSIC_DISC_WARD
  - MUSIC_DISC_11
  - MUSIC_DISC_WAIT
  - MUSIC_DISC_OTHERSIDE
  - MUSIC_DISC_5
  - MUSIC_DISC_PIGSTEP
  - DRAGON_HEAD
  - WITHER_SKELETON_SKULL
  - EXPERIENCE_BOTTLE
  - DRAGON_EGG

# Whitelist of items allowed in build mode (only used if restriction-mode is set to whitelist)
whitelist:
  # This is empty by default as we're using blacklist mode
  # Add items here if you switch to whitelist mode
